#!/usr/bin/env python3
"""Validate MO Japanization design/loadout ledgers against a generated source ledger.

Default mode checks ledger integrity and reports unresolved source references as
warnings. --strict promotes warnings to errors and is intended only after the
production Patch/loadout/generation rewrites exist.
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DECISION = REPO_ROOT / "Docs/Research/Data/MedievalOverhaulJapanizationDecisionLedger.csv"
DEFAULT_LOADOUT = REPO_ROOT / "Docs/Research/Data/MedievalOverhaulJapanizationLoadoutLedger.csv"
DEFAULT_RESEARCH_GRAPH = REPO_ROOT / "Docs/Research/Data/MedievalOverhaulJapanizationResearchGraph.csv"
DEFAULT_DBH_OVERLAY = REPO_ROOT / "Docs/Research/Data/MedievalOverhaulJapanizationDBHResearchOverlay.csv"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as fh:
        return list(csv.DictReader(fh))


def semi(value: str) -> list[str]:
    return [part.strip() for part in (value or "").split(";") if part.strip()]


def is_mo_owned(name: str) -> bool:
    return name.startswith("DankPyon_") or name.startswith("Dankpyon_")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", required=True, type=Path, help="CSV generated by generate_mo_japanization_source_ledger.py")
    ap.add_argument("--decision", type=Path, default=DEFAULT_DECISION)
    ap.add_argument("--loadout", type=Path, default=DEFAULT_LOADOUT)
    ap.add_argument("--research-graph", type=Path, default=DEFAULT_RESEARCH_GRAPH)
    ap.add_argument("--dbh-overlay", type=Path, default=DEFAULT_DBH_OVERLAY)
    ap.add_argument("--strict", action="store_true", help="promote unresolved warnings to errors")
    args = ap.parse_args()

    source = read_csv(args.source)
    decisions = read_csv(args.decision)
    loadouts = read_csv(args.loadout)
    research_graph = read_csv(args.research_graph)
    dbh_overlay = read_csv(args.dbh_overlay)

    errors: list[str] = []
    warnings: list[str] = []

    source_by_key: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    identities: set[str] = set()
    thing_defs: set[str] = set()
    pawn_kinds: set[str] = set()
    weapon_tags: set[str] = set()

    for row in source:
        key = (row.get("def_type", ""), row.get("def_name", ""))
        source_by_key[key].append(row)
        name = row.get("def_name", "")
        identities.add(name)
        if row.get("def_type") == "ThingDef":
            thing_defs.add(name)
        if row.get("def_type") == "PawnKindDef":
            pawn_kinds.add(name)
        weapon_tags.update(semi(row.get("weapon_tags", "")))

    # Target research-graph uniqueness / prerequisite integrity.
    research_by_name: dict[str, dict[str, str]] = {}
    for row in research_graph:
        name = row.get("research_def", "")
        if not name:
            errors.append("research graph contains blank research_def")
            continue
        if name in research_by_name:
            errors.append(f"duplicate research graph row: {name}")
        research_by_name[name] = row

    if len(research_graph) != 67:
        warnings.append(f"target research graph row count changed from audited 67: {len(research_graph)}")

    hidden_research_states = {"HIDE", "DETACH_VANILLA", "DETACH_OWNER"}
    for name, row in research_by_name.items():
        visibility = row.get("visibility", "")
        for parent in semi(row.get("target_prerequisites", "")):
            parent_row = research_by_name.get(parent)
            if parent_row is None:
                errors.append(f"research graph prerequisite is not in audited 67-node surface: {name} -> {parent}")
                continue
            if visibility == "VISIBLE" and parent_row.get("visibility") in hidden_research_states:
                errors.append(
                    f"visible research depends on hidden/detached research: "
                    f"{name} -> {parent} ({parent_row.get('visibility')})"
                )

    # DBH overlay structural integrity. This validates the target overlay itself;
    # source existence/runtime behavior belongs to the DBH compatibility profile.
    dbh_by_name: dict[str, dict[str, str]] = {}
    for row in dbh_overlay:
        name = row.get("def_name", "")
        if not name:
            errors.append("DBH overlay contains blank def_name")
            continue
        if name in dbh_by_name:
            errors.append(f"duplicate DBH overlay row: {name}")
        dbh_by_name[name] = row

    allowed_external_dbh_parents = {"Electricity"}
    for name, row in dbh_by_name.items():
        visibility = row.get("visibility", "")
        for parent in semi(row.get("target_prerequisites", "")):
            if parent in dbh_by_name:
                parent_visibility = dbh_by_name[parent].get("visibility", "")
                if visibility == "VISIBLE" and parent_visibility == "HIDE":
                    errors.append(f"visible DBH overlay entry depends on hidden DBH entry: {name} -> {parent}")
                continue
            if parent in research_by_name:
                parent_visibility = research_by_name[parent].get("visibility", "")
                if visibility == "VISIBLE" and parent_visibility != "VISIBLE":
                    errors.append(
                        f"visible DBH overlay entry depends on non-visible MO research: "
                        f"{name} -> {parent} ({parent_visibility})"
                    )
                continue
            if parent not in allowed_external_dbh_parents:
                errors.append(f"DBH overlay prerequisite is unresolved: {name} -> {parent}")

    # Explicit architecture invariants from the approved target graph.
    for child, forbidden_parent in (
        ("PlateArmor", "DankPyon_ChainArmor"),
        ("DankPyon_Steel", "DankPyon_Alchemy"),
        ("DankPyon_Gunpowder", "DankPyon_Alchemy"),
        ("DankPyon_Exploration", "DankPyon_CarrierBirds"),
    ):
        child_row = research_by_name.get(child)
        if child_row and forbidden_parent in semi(child_row.get("target_prerequisites", "")):
            errors.append(f"forbidden target prerequisite remains: {child} -> {forbidden_parent}")

    for row in dbh_overlay:
        if row.get("visibility") != "VISIBLE":
            continue
        parents = set(semi(row.get("target_prerequisites", "")))
        if "DankPyon_Windmill" in parents:
            errors.append(f"visible DBH overlay entry still depends on hidden Windmill: {row.get('def_name')}")
        if "Plumbing" in parents:
            errors.append(f"visible DBH overlay entry still depends on Plumbing: {row.get('def_name')}")

    # Decision-ledger uniqueness and MO-owned Def existence.
    seen_decisions: set[tuple[str, str]] = set()
    for row in decisions:
        key = (row.get("def_type", ""), row.get("def_name", ""))
        if key in seen_decisions:
            errors.append(f"duplicate decision row: {key[0]}:{key[1]}")
        seen_decisions.add(key)

        name = key[1]
        if is_mo_owned(name) and key not in source_by_key:
            errors.append(f"decision refers to missing MO source identity: {key[0]}:{name}")

        if row.get("decision") == "PATCH_MECHANICS":
            warnings.append(f"mechanical patch requires explicit implementation/runtime test: {name}")

    # Loadout-ledger uniqueness and reference integrity.
    seen_loadouts: set[tuple[str, str]] = set()
    removed_apparel: set[str] = set()
    removed_weapon_tags: set[str] = set()
    added_weapon_tags: set[str] = set()

    for row in loadouts:
        pawn = row.get("pawn_kind_or_template", "")
        action = row.get("action", "")
        key = (pawn, action)
        if key in seen_loadouts:
            errors.append(f"duplicate loadout action: {pawn}:{action}")
        seen_loadouts.add(key)

        if is_mo_owned(pawn) and pawn not in pawn_kinds:
            errors.append(f"loadout refers to missing MO PawnKind identity: {pawn}")

        for field in ("remove_apparel_required", "add_apparel_required"):
            vals = semi(row.get(field, ""))
            if len(vals) != len(set(vals)):
                errors.append(f"duplicate item in {pawn}:{field}")
            for name in vals:
                if is_mo_owned(name) and name not in thing_defs:
                    errors.append(f"{pawn}:{field} refers to missing MO ThingDef: {name}")
            if field == "remove_apparel_required":
                removed_apparel.update(vals)

        for field in ("remove_weapon_tags", "add_weapon_tags"):
            vals = semi(row.get(field, ""))
            if len(vals) != len(set(vals)):
                errors.append(f"duplicate tag in {pawn}:{field}")
            for tag in vals:
                if is_mo_owned(tag) and tag not in weapon_tags:
                    errors.append(f"{pawn}:{field} refers to unknown MO weapon tag: {tag}")
            if field == "remove_weapon_tags":
                removed_weapon_tags.update(vals)
            else:
                added_weapon_tags.update(vals)

    # Source-reference risk report for hidden Defs.
    for row in decisions:
        if row.get("decision") != "HIDE":
            continue
        key = (row.get("def_type", ""), row.get("def_name", ""))
        matches = source_by_key.get(key, [])
        if not matches:
            continue
        name = key[1]
        pawn_refs = sum(int(m.get("ref_pawnkind") or 0) for m in matches)
        gen_refs = sum(int(m.get("ref_generation") or 0) for m in matches)

        if pawn_refs and name not in removed_apparel:
            # Weapon references are usually indirect through weaponTags. Treat a
            # hidden weapon as mitigated only when all of its MO weapon tags are
            # explicitly removed somewhere in the loadout ledger.
            tags = set()
            for m in matches:
                tags.update(semi(m.get("weapon_tags", "")))
            unresolved_tags = {t for t in tags if is_mo_owned(t) and t not in removed_weapon_tags}
            if not tags or unresolved_tags:
                detail = f" tags={';'.join(sorted(unresolved_tags))}" if unresolved_tags else ""
                warnings.append(f"hidden Def still has {pawn_refs} PawnKind source ref(s): {name}{detail}")

        if gen_refs:
            warnings.append(f"hidden Def still has {gen_refs} generation source ref(s): {name}")

    # A tag added by a Japanized loadout must not have zero source weapon carriers.
    for tag in sorted(added_weapon_tags):
        if is_mo_owned(tag):
            carriers = [r for r in source if tag in semi(r.get("weapon_tags", ""))]
            if not carriers:
                errors.append(f"added weapon tag has no MO source carrier: {tag}")

    print(
        f"source_rows={len(source)} decisions={len(decisions)} "
        f"loadout_rows={len(loadouts)} research_rows={len(research_graph)} "
        f"dbh_overlay_rows={len(dbh_overlay)}"
    )
    print(f"errors={len(errors)} warnings={len(warnings)} strict={args.strict}")

    for msg in errors:
        print("ERROR: " + msg)
    for msg in warnings:
        print("WARN: " + msg)

    if errors:
        return 1
    if args.strict and warnings:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
